server:
  port: 8080
spring:
#模版配置
  thymeleaf:
    cache: false
    encoding: utf-8
    prefix: classpath:/static/templates
    mode: HTML5
    suffix: .html
    servlet:
      content-type: text/html
    check-template: false

#zuul config
zuul:
  routes:
    api-student:
      path: /api/student/**
      #url: http://www.baidu.com
      serviceId: STUDENT
    api-teacher:
      path: /api/teacher/**
      serviceId: TEACHER

service:
  student:
    app:
      name: STUDENT

#logbook.write.level=info
#logbook.format.style=http
#logbook.filter.enabled=false